# Generated by Django 3.2.9 on 2021-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Better'), (3, 'Best'), (4, 'Not Good'), (5, 'Avarage'), (6, 'Not Bad'), (7, 'Reasonable Performance')]),
        ),
    ]
