# Generated by Django 3.2.9 on 2021-12-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='num_stars',
            new_name='Rating',
        ),
    ]
