# Generated by Django 3.2.9 on 2021-12-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0003_rename_num_stars_album_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=15)),
                ('Last_Name', models.CharField(blank=True, max_length=10)),
                ('Address', models.CharField(blank=True, max_length=30)),
                ('cell', models.IntegerField(blank=True)),
                ('First_Admission_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
