# Generated by Django 3.2.9 on 2021-12-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0005_auto_20211206_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='Address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='cell',
            field=models.IntegerField(max_length=11),
        ),
    ]
