# Generated by Django 3.2.9 on 2021-12-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApplication', '0007_alter_studentlist_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='First_Admission_Date',
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='Address',
            field=models.CharField(max_length=20),
        ),
    ]
